## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# Drop the 'EIN' and 'NAME' columns and assign the result back to the DataFrame
application_df = application_df.drop(columns=['EIN', 'NAME'])

# Display the first few rows of the updated DataFrame
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
print(application_df.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
value_counts=application_df['APPLICATION_TYPE'].value_counts()
print(value_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Define the threshold
threshold = 200  # Replace values below this count with "Other"

# Calculate value counts
value_counts = application_df['APPLICATION_TYPE'].value_counts()

# Identify application types to replace
application_types_to_replace = value_counts[value_counts < threshold].index

# Replace in dataframe
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace, "Other")

# Check to make sure replacement was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts=application_df['CLASSIFICATION'].value_counts()
print(value_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print(value_counts[value_counts > 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Define the threshold

threshold = 700

# Identify classifications to replace with "Other"
classifications_to_replace = value_counts[value_counts < threshold].index

# Replace in dataframe
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(classifications_to_replace, "Other")

# Display the updated value counts to check if the replacement was successful
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts=application_df['ASK_AMT'].value_counts()
print(value_counts)

ASK_AMT
5000        25398
10478           3
15583           3
63981           3
6725            3
            ...
5371754         1
30060           1
43091152        1
18683           1
36500179        1
Name: count, Length: 8747, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Scale ASK_AMT using Min-Max scaling
scaler = MinMaxScaler()
application_df['ASK_AMT'] = scaler.fit_transform(application_df[['ASK_AMT']])

In [ ]:
# Convert categorical data to numeric with pd.get_dummies and ensure all data is of type int
application_dummies = pd.get_dummies(application_df[["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "STATUS", "INCOME_AMT", "SPECIAL_CONSIDERATIONS"]]).astype(int)

# Step 3: Combine the scaled ASK_AMT column with the one-hot encoded data and the target column
application_df_scaled = pd.concat([
    application_df.index.to_frame(),  # Keep the index as a column
    application_dummies,              # One-hot encoded categorical data
    application_df["ASK_AMT"],        # Scaled ASK_AMT column
    application_df["IS_SUCCESSFUL"]   # Target column
], axis=1)

# Display the combined DataFrame
application_df_scaled.head()

,0,STATUS,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT,IS_SUCCESSFUL
0,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0.000000e+00,1
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1.204843e-05,1
2,2,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0.000000e+00,0
3,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1.967945e-07,1
4,4,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,1.600293e-05,1

In [ ]:
application_df_scaled.columns

Index([                             0,                       'STATUS',
             'APPLICATION_TYPE_Other',         'APPLICATION_TYPE_T10',
               'APPLICATION_TYPE_T19',          'APPLICATION_TYPE_T3',
                'APPLICATION_TYPE_T4',          'APPLICATION_TYPE_T5',
                'APPLICATION_TYPE_T6',          'APPLICATION_TYPE_T7',
                'APPLICATION_TYPE_T8', 'AFFILIATION_CompanySponsored',
          'AFFILIATION_Family/Parent',      'AFFILIATION_Independent',
               'AFFILIATION_National',            'AFFILIATION_Other',
               'AFFILIATION_Regional',         'CLASSIFICATION_C1000',
               'CLASSIFICATION_C1200',         'CLASSIFICATION_C2000',
               'CLASSIFICATION_C2100',         'CLASSIFICATION_C3000',
               'CLASSIFICATION_C7000',         'CLASSIFICATION_Other',
             'USE_CASE_CommunityServ',           'USE_CASE_Heathcare',
                     'USE_CASE_Other',        'USE_CASE_Preservation',
                'USE_CASE_ProductDev',     'ORGANIZATION_Association',
          'ORGANIZATION_Co-operative',     'ORGANIZATION_Corporation',
                 'ORGANIZATION_Trust',                 'INCOME_AMT_0',
                  'INCOME_AMT_1-9999',       'INCOME_AMT_10000-24999',
           'INCOME_AMT_100000-499999',           'INCOME_AMT_10M-50M',
                   'INCOME_AMT_1M-5M',       'INCOME_AMT_25000-99999',
                    'INCOME_AMT_50M+',            'INCOME_AMT_5M-10M',
           'SPECIAL_CONSIDERATIONS_N',     'SPECIAL_CONSIDERATIONS_Y',
                            'ASK_AMT',                'IS_SUCCESSFUL'],
      dtype='object')

In [ ]:
#application_df_scaled = application_df_scaled.drop(columns=['APPLICATION_TYPE_Other', 'CLASSIFICATION_Other'])
application_df_scaled.head()

,0,STATUS,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT,IS_SUCCESSFUL
0,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0.000000e+00,1
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1.204843e-05,1
2,2,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0.000000e+00,0
3,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1.967945e-07,1
4,4,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,1.600293e-05,1

In [ ]:
# Split our preprocessed data into our features and target arrays
# The y variable should focus on the target column
y = application_df_scaled['IS_SUCCESSFUL']

# The X variable should include all features except the target
X = application_df_scaled.drop(columns=['IS_SUCCESSFUL'])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
# Ensure all column names are strings
X.columns = X.columns.astype(str)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Display the scaled training data
X_train_scaled[:5]

array([[-1.4323565 ,  0.01247081, -0.09245003, -0.12228508, -0.1781152 ,
         0.51672515, -0.21760398, -0.18496974, -0.19431986, -0.14670825,
        -0.14656994, -0.91834288, -0.0389666 ,  0.92382231, -0.03180805,
        -0.00881785, -0.01870803, -1.00953072,  2.46906376, -0.46603173,
        -0.24261548, -0.24063304, -0.14890525, -0.21425135, -0.10917545,
        -0.06612829, -0.00881785,  0.46967342, -0.44374596, -0.65143168,
         8.16668457, -0.03795283, -1.47758905,  0.64073318, -0.14794773,
        -0.13069239, -0.3318628 , -0.08156334, -0.1687197 , -0.35102803,
        -0.06401969, -0.07476688,  0.02718742, -0.02718742, -0.03058697],
       [-1.6241755 ,  0.01247081, -0.09245003, -0.12228508, -0.1781152 ,
         0.51672515, -0.21760398, -0.18496974, -0.19431986, -0.14670825,
        -0.14656994,  1.08891791, -0.0389666 , -1.08245925, -0.03180805,
        -0.00881785, -0.01870803,  0.99055926, -0.40501182, -0.46603173,
        -0.24261548, -0.24063304, -0.14890525, -0.21425135, -0.10917545,
        -0.06612829, -0.00881785,  0.46967342, -0.44374596, -0.65143168,
        -0.12244871, -0.03795283,  0.67677816,  0.64073318, -0.14794773,
        -0.13069239, -0.3318628 , -0.08156334, -0.1687197 , -0.35102803,
        -0.06401969, -0.07476688,  0.02718742, -0.02718742, -0.03058697],
       [ 1.5143872 ,  0.01247081, -0.09245003, -0.12228508, -0.1781152 ,
        -1.93526483, -0.21760398, -0.18496974,  5.14615448, -0.14670825,
        -0.14656994, -0.91834288, -0.0389666 ,  0.92382231, -0.03180805,
        -0.00881785, -0.01870803, -1.00953072, -0.40501182,  2.14577662,
        -0.24261548, -0.24063304, -0.14890525, -0.21425135, -0.10917545,
        -0.06612829, -0.00881785, -2.12913902,  2.25354164,  1.53508039,
        -0.12244871, -0.03795283, -1.47758905,  0.64073318, -0.14794773,
        -0.13069239, -0.3318628 , -0.08156334, -0.1687197 , -0.35102803,
        -0.06401969, -0.07476688,  0.02718742, -0.02718742, -0.03058697],
       [-1.03660361,  0.01247081, -0.09245003, -0.12228508, -0.1781152 ,
         0.51672515, -0.21760398, -0.18496974, -0.19431986, -0.14670825,
        -0.14656994, -0.91834288, -0.0389666 ,  0.92382231, -0.03180805,
        -0.00881785, -0.01870803, -1.00953072, -0.40501182,  2.14577662,
        -0.24261548, -0.24063304, -0.14890525, -0.21425135, -0.10917545,
        -0.06612829, -0.00881785,  0.46967342, -0.44374596, -0.65143168,
        -0.12244871, -0.03795283,  0.67677816, -1.56071205, -0.14794773,
        -0.13069239,  3.01329343, -0.08156334, -0.1687197 , -0.35102803,
        -0.06401969, -0.07476688,  0.02718742, -0.02718742, -0.03055371],
       [ 1.09026529,  0.01247081, -0.09245003, -0.12228508, -0.1781152 ,
         0.51672515, -0.21760398, -0.18496974, -0.19431986, -0.14670825,
        -0.14656994, -0.91834288, -0.0389666 ,  0.92382231, -0.03180805,
        -0.00881785, -0.01870803,  0.99055926, -0.40501182, -0.46603173,
        -0.24261548, -0.24063304, -0.14890525, -0.21425135, -0.10917545,
        -0.06612829, -0.00881785,  0.46967342, -0.44374596, -0.65143168,
        -0.12244871, -0.03795283,  0.67677816, -1.56071205, -0.14794773,
        -0.13069239, -0.3318628 , -0.08156334, -0.1687197 ,  2.84877533,
        -0.06401969, -0.07476688,  0.02718742, -0.02718742, -0.03037698]])

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

nn = tf.keras.models.Sequential()

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(
    filepath='model_weights_epoch_{epoch:02d}.weights.h5',
    save_weights_only=True,
    save_freq='epoch'  # Save after each epoch; you can adjust this based on your needs
)

In [ ]:
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam, RMSprop, SGD, Adamax

# Updated Model Architecture
nn = Sequential()
nn.add(Input(shape=(45,)))
nn.add(Dense(units=1512, activation="relu"))
nn.add(Dropout(0.3))  # Adding Dropout to prevent overfitting
nn.add(Dense(units=512, activation="relu"))
nn.add(Dropout(0.3))  # Adding Dropout to prevent overfitting
nn.add(Dense(units=256, activation="relu"))
nn.add(Dense(units=1, activation="sigmoid"))

# Experiment with different optimizers
    #'Adam': Adam(learning_rate=0.001),
    #'RMSprop': RMSprop(learning_rate=0.001),
    #'SGD': SGD(learning_rate=0.01, momentum=0.9),
# Iterate through each optimizer to find the best one: Adamax had best results
optimizers = {
    'Adamax': Adamax(learning_rate=0.002)
}

for name, optimizer in optimizers.items():
    print(f"\nTraining with {name} optimizer...")
    nn.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy"])

    # Callbacks
    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.00001)

    # Train the model
    nn.fit(X_train_scaled, y_train, epochs=100, validation_data=(X_test_scaled, y_test),
              callbacks=[early_stopping, reduce_lr], verbose=1)

    # Evaluate the model
    loss, accuracy = nn.evaluate(X_test_scaled, y_test, verbose=0)
    print(f"{name} Optimizer - Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

Training with Adamax optimizer...
Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 24s 28ms/step - accuracy: 0.7142 - loss: 0.5834 - val_accuracy: 0.7258 - val_loss: 0.5635 - learning_rate: 0.0020
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 21ms/step - accuracy: 0.7310 - loss: 0.5523 - val_accuracy: 0.7247 - val_loss: 0.5553 - learning_rate: 0.0020
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 27ms/step - accuracy: 0.7323 - loss: 0.5531 - val_accuracy: 0.7254 - val_loss: 0.5552 - learning_rate: 0.0020
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 36s 22ms/step - accuracy: 0.7333 - loss: 0.5489 - val_accuracy: 0.7268 - val_loss: 0.5570 - learning_rate: 0.0020
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 23s 25ms/step - accuracy: 0.7325 - loss: 0.5499 - val_accuracy: 0.7256 - val_loss: 0.5549 - learning_rate: 0.0020
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.7335 - loss: 0.5467 - val_accuracy: 0.7275 - val_loss: 0.5521 - learning_rate: 0.0020
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 20ms/step - accuracy: 0.7341 - loss: 0.5475 - val_accuracy: 0.7280 - val_loss: 0.5565 - learning_rate: 0.0020
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 26ms/step - accuracy: 0.7354 - loss: 0.5429 - val_accuracy: 0.7290 - val_loss: 0.5507 - learning_rate: 0.0020
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 38s 23ms/step - accuracy: 0.7348 - loss: 0.5435 - val_accuracy: 0.7297 - val_loss: 0.5547 - learning_rate: 0.0020
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 25ms/step - accuracy: 0.7399 - loss: 0.5374 - val_accuracy: 0.7279 - val_loss: 0.5573 - learning_rate: 0.0020
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 20ms/step - accuracy: 0.7408 - loss: 0.5343 - val_accuracy: 0.7243 - val_loss: 0.5514 - learning_rate: 0.0020
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 25s 26ms/step - accuracy: 0.7348 - loss: 0.5396 - val_accuracy: 0.7287 - val_loss: 0.5511 - learning_rate: 0.0020
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.7451 - loss: 0.5334 - val_accuracy: 0.7294 - val_loss: 0.5498 - learning_rate: 0.0020
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 18s 21ms/step - accuracy: 0.7472 - loss: 0.5315 - val_accuracy: 0.7279 - val_loss: 0.5542 - learning_rate: 0.0020
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 20s 25ms/step - accuracy: 0.7409 - loss: 0.5347 - val_accuracy: 0.7276 - val_loss: 0.5485 - learning_rate: 0.0020
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 23ms/step - accuracy: 0.7433 - loss: 0.5325 - val_accuracy: 0.7273 - val_loss: 0.5480 - learning_rate: 0.0020
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 18s 23ms/step - accuracy: 0.7418 - loss: 0.5375 - val_accuracy: 0.7287 - val_loss: 0.5492 - learning_rate: 0.0020
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 25ms/step - accuracy: 0.7386 - loss: 0.5347 - val_accuracy: 0.7308 - val_loss: 0.5492 - learning_rate: 0.0020
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.7437 - loss: 0.5351 - val_accuracy: 0.7314 - val_loss: 0.5503 - learning_rate: 0.0020
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 21s 26ms/step - accuracy: 0.7455 - loss: 0.5309 - val_accuracy: 0.7279 - val_loss: 0.5488 - learning_rate: 0.0020
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 36s 20ms/step - accuracy: 0.7479 - loss: 0.5245 - val_accuracy: 0.7313 - val_loss: 0.5509 - learning_rate: 0.0020
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 24s 25ms/step - accuracy: 0.7469 - loss: 0.5258 - val_accuracy: 0.7329 - val_loss: 0.5473 - learning_rate: 4.0000e-04
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.7475 - loss: 0.5269 - val_accuracy: 0.7317 - val_loss: 0.5469 - learning_rate: 4.0000e-04
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 20s 24ms/step - accuracy: 0.7498 - loss: 0.5218 - val_accuracy: 0.7321 - val_loss: 0.5474 - learning_rate: 4.0000e-04
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 26ms/step - accuracy: 0.7468 - loss: 0.5198 - val_accuracy: 0.7305 - val_loss: 0.5468 - learning_rate: 4.0000e-04
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 21ms/step - accuracy: 0.7517 - loss: 0.5193 - val_accuracy: 0.7299 - val_loss: 0.5473 - learning_rate: 4.0000e-04
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 20s 25ms/step - accuracy: 0.7462 - loss: 0.5221 - val_accuracy: 0.7305 - val_loss: 0.5482 - learning_rate: 4.0000e-04
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 17s 21ms/step - accuracy: 0.7504 - loss: 0.5176 - val_accuracy: 0.7306 - val_loss: 0.5482 - learning_rate: 4.0000e-04
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 23ms/step - accuracy: 0.7457 - loss: 0.5212 - val_accuracy: 0.7317 - val_loss: 0.5486 - learning_rate: 4.0000e-04
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 22s 25ms/step - accuracy: 0.7499 - loss: 0.5205 - val_accuracy: 0.7317 - val_loss: 0.5467 - learning_rate: 4.0000e-04
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.7437 - loss: 0.5257 - val_accuracy: 0.7306 - val_loss: 0.5472 - learning_rate: 8.0000e-05
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.7522 - loss: 0.5130 - val_accuracy: 0.7310 - val_loss: 0.5472 - learning_rate: 8.0000e-05
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 20s 23ms/step - accuracy: 0.7503 - loss: 0.5160 - val_accuracy: 0.7312 - val_loss: 0.5476 - learning_rate: 8.0000e-05
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 21ms/step - accuracy: 0.7490 - loss: 0.5179 - val_accuracy: 0.7303 - val_loss: 0.5478 - learning_rate: 8.0000e-05
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 23s 24ms/step - accuracy: 0.7552 - loss: 0.5152 - val_accuracy: 0.7308 - val_loss: 0.5479 - learning_rate: 8.0000e-05
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 18s 23ms/step - accuracy: 0.7464 - loss: 0.5174 - val_accuracy: 0.7306 - val_loss: 0.5479 - learning_rate: 1.6000e-05
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 19s 20ms/step - accuracy: 0.7512 - loss: 0.5146 - val_accuracy: 0.7307 - val_loss: 0.5479 - learning_rate: 1.6000e-05
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 25s 26ms/step - accuracy: 0.7518 - loss: 0.5135 - val_accuracy: 0.7307 - val_loss: 0.5479 - learning_rate: 1.6000e-05
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 40s 25ms/step - accuracy: 0.7559 - loss: 0.5122 - val_accuracy: 0.7305 - val_loss: 0.5479 - learning_rate: 1.6000e-05
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 37s 20ms/step - accuracy: 0.7523 - loss: 0.5156 - val_accuracy: 0.7305 - val_loss: 0.5479 - learning_rate: 1.6000e-05
Adamax Optimizer - Loss: 0.5467, Accuracy: 0.7317

In [ ]:
# Export our model to HDF5 file
nn.save('my_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.